#include "editor.h"

TCHAR* gpc_playstyle20[22] = { _T("None"),
						  _T("Goal Poacher"),
						  _T("Dummy Runner"),
						  _T("Fox in the Box"),
						  _T("Target Man"),
						  _T("Creative Playmaker"),
						  _T("Prolific Winger"),
						  _T("Roaming Flank"),
						  _T("Crossing Specialist"),
						  _T("Classic No. 10"),
						  _T("Hole Player"),
						  _T("Box to Box"),
						  _T("The Destroyer"),
						  _T("Orchestrator"),
						  _T("Anchor Man"),
						  _T("Offensive Fullback"),
						  _T("Fullback Finisher"),
						  _T("Defensive Fullback"),
						  _T("Build Up"),
						  _T("Extra Frontman"),
						  _T("Offensive Goalkeeper"),
						  _T("Defensive Goalkeeper") };

TCHAR* gpc_playstyle19[22] = { _T("None"),
						  _T("Goal Poacher"),
						  _T("Dummy Runner"),
						  _T("Fox in the Box"),
						  _T("Target Man"),
						  _T("Creative Playmaker"),
						  _T("Prolific Winger"),
						  _T("Roaming Flank"),
						  _T("Crossing Specialist"),
						  _T("Classic No. 10"),
						  _T("Hole Player"),
						  _T("Box to Box"),
						  _T("The Destroyer"),
						  _T("Orchestrator"),
						  _T("Anchor Man"),
						  _T("Build Up"),
						  _T("Offensive Fullback"),
						  _T("Fullback Finisher"),
						  _T("Defensive Fullback"),
						  _T("Extra Frontman"),
						  _T("Offensive Goalkeeper"),
						  _T("Defensive Goalkeeper") };

TCHAR* gpc_playstyle18[18] = { _T("None"),
					  _T("Goal Poacher"),
					  _T("Dummy Runner"),
					  _T("Fox in the Box"),
					  _T("Prolific Winger"),
					  _T("Classic No. 10"),
					  _T("Hole Player"),
					  _T("Box to Box"),
					  _T("Anchor Man"),
					  _T("The Destroyer"),
					  _T("Extra Frontman"),
					  _T("Offensive Fullback"),
					  _T("Defensive Fullback"),
					  _T("Target Man"),
					  _T("Creative Playmaker"),
					  _T("Build Up"),
					  _T("Offensive Goalkeeper"),
					  _T("Defensive Goalkeeper") };

TCHAR* gpc_positions[13] = { _T("Goalkeeper"),
							_T("Center Back"),
							_T("Left Back"),
							_T("Right Back"),
							_T("Defensive Midfielder"),
							_T("Center Midfielder"),
							_T("Left Midfielder"),
							_T("Right Midfielder"),
							_T("Attacking Midfielder"),
							_T("Left Wing Forward"),
							_T("Right Wing Forward"),
							_T("Second Striker"),
							_T("Centre Forward") };

TCHAR* gpc_pos_short[13] = { _T("GK"),_T("CB"),_T("LB"),_T("RB"),_T("DMF"),_T("CMF"),_T("LMF"),_T("RMF"),_T("AMF"),
					       _T("LWF"),_T("RWF"),_T("SS"),_T("CF") };

